bash:
  shaper:
    # one of ["router", "wondershaper", "shaper", "tc_computer"]
    method: "tc_computer"
    # only applied when shaper method is "router"
    router_ip: ""
    router_user: ""
    # only applied when shaper method is "tc_computer"
    computer_ip: ""
    computer_user: ""
    # only applied when shaper method is "wondeshaper" or "shaper"
    interface: "enp2s0"
  captureInterface: "enp2s0"
  videoFile: "media/test.mp4"
  devVideo: "/dev/video0"


python:
  mtr:
    enabled: false
    endpoint: ""
  # Adds an extra delay before closing chrome
  # This is intended to be used on experiments
  # that aim to gather dump webrtc from both sides(sender, receiver)
  # It gives more time to the one who is running
  # the experiment to go to the other machine
  # which will not download the webrtc dump
  # automatically and do it manually.
  receiverWait:
    enabled: false
    # 10 seconds
    time: 10000
  notify:
    enabled: false
    destination: ""
    port: 12345
  # one of ["Low", "Medium", "High", "High Definition"]
  videoQuality: "High Definition"
