app:
  logging:
    level: INFO
  # Adds an extra delay before closing chrome
  # This is intended to be used on experiments
  # that aim to gather dump webrtc from both sides(sender, receiver)
  # It gives more time to the one who is running
  # the experiment to go to the other machine
  # which will not download the webrtc dump
  # automatically and do it manually.
  receiverWait:
    enabled: false
    # 10 seconds
    time: 10000
  notify:
    enabled: false
    destination: ''
    port: 12345
  shaper:
    endpoint: ''
    port: 6666
  tools:
    virtualCamera:
      videoFile: 'media/test.mp4'
      devVideo: '/dev/video2'
  browsers:
    chrome:
      fakeDevice: false
      internalLogs: false
  platforms:
    elos:
      # one of ["Low", "Medium", "High", "High Definition"]
      videoQuality: "High Definition"
      joinMicrophone: false
      mtr:
        enabled: false
        endpoint: ""
